### ISSUE TITLE
Рассмотреть готовые решения для построения бэкенда

### ISSUE THREAD

**Issue by EgorRazumilov** [Aorta-Detectors/Aorta-Detection#13]
Возможно, существуют уже подходящие нам готовые решения для выстраивания бэкенда. Хотелось бы поресерчить такие вещи. 
Примерный список (может дополняться):

1. EntResourceMng / ERPlaning
2. CRM ретроспектива (HealthCare CRM)
3. TicketSystem / HelpDesk
4. Bisness Process Managment System поверх SRM - перспектива (удобно использовать для аналитиков)
5. Различные бизнес фреймворки, например HeadlessCMS - формируется бэкенд
6. Различные BaaS решения

**Comment by dszharikov** [comment]
Я сформировал следующие необходимые функциональные требования для backend:
1) Регистрация и авторизация врачей (две роли врачей: кардиолога и рентгенолога)
2) Составление и сохранение карты пациента (кардиолога) с основной информацией о пациенте
3) Подготовка обследования пациента (диагноз, анамнез и другие данные, которые должны быть заполнены кардиологом во время обследования пациента) для кардиолога
4) Добавление большого файла DICOM к обследованию пациента (кардиолог и рентгенолог могут добавить файл)
5) Загрузка из внешних источников (external API) изображений обследования пациента и демонстрация изображений. Возможность оставлять отзывы о качестве изображений
6) Возможность просмотра другими врачами (кардиологами и радиологами) обследований пациентов и комментирования обследований (диагнозов)
7) Протоколирование всех действий пользователя

**Comment by dszharikov** [comment]
Провел анализ самых популярных опенсурс ERP, которые могут быть настроены для выполнения необходимых функциональностей:

**Odoo:**

**Регистрация и авторизация**: Odoo предоставляет встроенную систему аутентификации и авторизации с возможностью настройки различных ролей пользователя.
**Составление карты пациента**: Можно создать пользовательские модули и объекты для хранения информации о пациентах.
**Подготовка обследования пациента**: Аналогично, можно создать пользовательские модули для хранения информации о медицинских записях.
**Добавление DICOM-файлов**: Возможно интегрировать библиотеки для обработки DICOM-файлов.
Загрузка из внешних источников: Odoo позволяет создавать пользовательские модули для интеграции с внешними API.
**Возможность просмотра другими врачами**: Разрешения и правила доступа можно настроить на уровне ролей пользователей.
**Протоколирование(Логирование)**: Odoo имеет систему журналирования событий и действий пользователей.

**ERPNext:**

**Регистрация и авторизация**: ERPNext предоставляет систему аутентификации и авторизации с многоуровневыми ролями.
**Составление карты пациента**: Можно настроить пользовательские поля для хранения информации о пациентах.
**Подготовка обследования пациента**: Данная ERP позволяет создавать пользовательские документы для хранения медицинских записей.
**Добавление DICOM-файлов**: Необходима интеграция с библиотеками обработки DICOM-файлов.
**Загрузка из внешних источников**: Можно настраивать интеграции с API для загрузки данных и изображений.
**Возможность просмотра другими врачами**: Права доступа и роли могут быть настроены.
**Протоколирование(Логирование)**: ERPNext имеет журнал событий для протоколирования действий.

**Comment by dszharikov** [comment]
Время, необходимое для адаптации данных ERP-систем, зависит от опыта команды разработчиков. Среднее время адаптации от 3-х недель (смотрел примеры других компаний по адаптации данных ERP под нужды бизнеса). Учитывая, что команда разработчиков небольшая и без большого опыта разработки backend, я считаю, что разработка MVP с нуля займет меньше времени. Использование библиотек облегчит решение многих задач из разработки

**Comment by dszharikov** [comment]
Проанализировал различные CMS и описал ниже как реализовать необходимые функциональные требования с использованием Headless CMS

**Регистрация и авторизация врачей:**
Можно использовать встроенные механизмы аутентификации CMS или интегрировать сторонние сервисы для регистрации и авторизации врачей. Можно настроить роли врачей в CMS.

**Составление и сохранение карты пациента:**
Можно создать пользовательские поля для хранения информации о пациентах. Они могут включать в себя текстовые поля, флажки (bool) и связи с другими записями, такими как диагнозы.

**Подготовка обследования пациента:**
Можно добавить пользовательские поля для записи диагнозов, анамнеза и другой информации, которую кардиолог должен вводить.

**Добавление DICOM-файлов:**
Можно использовать пользовательские поля для загрузки DICOM-файлов. Обязательно нужно будет проверить ограничения по размеру файла и формату, так как DICOM-файлы могут быть большими.

**Загрузка из внешних источников и отзывы:**
Можно создать интеграцию с внешними API для загрузки изображений обследования. Добавьте возможность для пользователей оставлять комментарии и отзывы. Это требует навыки программирования и знания о работе с внешними API.

**Просмотр другими врачами и комментирование:**
Можно настроить доступ и роли других врачей для просмотра и комментирования записей. CMS должна обеспечивать правила доступа и аутентификацию.

**Протоколирование:**
Headless CMS имеет встроенные средства аудита и протоколирования. Можно подключить их и настроить их для отслеживания действий пользователей.

Мое мнение: Возможно, потребуется несколько недель - месяц для полной настройки CMS с учетом всех требований.

**Comment by dszharikov** [comment]
Провел сравнение и анализ лучших опенсурс сервисов на основе TicketSystem / HelpDesk, которые смогут реализовать "из коробки" нужные функциональные требования.

Ниже представлен анализ двух популярных сервисов: OTRS и Zammad.

**OTRS:**

**Регистрация и авторизация**: OTRS предоставляет систему аутентификации и авторизации с возможностью настройки ролей и разрешений для пользователей.
**Составление карты пациента**: OTRS может быть настроен для создания карточек пациентов с пользовательскими полями для хранения информации.
**Подготовка обследования пациента**: Можно создать тикеты для каждого обследования и внести необходимую информацию в текстовые поля.
**Добавление DICOM-файлов**: OTRS позволяет загружать и хранить вложения к тикетам, но обработка DICOM-файлов может потребовать дополнительной интеграции.
**Загрузка из внешних источников**: OTRS поддерживает интеграции, и вы можете настроить их для загрузки данных из внешних API.
**Возможность просмотра другими врачами**: OTRS имеет систему разрешений и комментариев.
**Протоколирование**: OTRS ведет журнал событий и действий пользователей.

**Zammad:**

**Регистрация и авторизация**: Zammad предоставляет систему аутентификации и авторизации с настройкой ролей пользователей.
**Составление карты пациента**: Zammad может быть настроен для создания карточек пациентов с пользовательскими полями.
**Подготовка обследования пациента**: В Zammad можно создавать тикеты для обследования и вносить информацию в текстовые поля.
**Добавление DICOM-файлов**: Zammad поддерживает вложения к тикетам, но может потребоваться интеграция для обработки DICOM-файлов.
**Загрузка из внешних источников**: Zammad поддерживает интеграции, которые могут быть настроены для загрузки данных из внешних API.
**Возможность просмотра другими врачами**: Zammad позволяет настраивать разрешения и комментарии для тикетов.
**Протоколирование (Логирование)**: Zammad имеет функциональность аудита для протоколирования действий пользователей.

Мое мнение, касательно интеграции Zammad и OTRS: интеграция займет меньше времени, но решения платные. Есть бесплатные версии (созданные адаптированные внешними разработчиками). Они хорошо подойдут для дальнейшего расширения сервиса

**Comment by dszharikov** [comment]
Заключение:
Для реализации MVP в использовании описанных выше решений нет необходимости. Но при дальнейшем расширении проекта необходимость использования возрастает, так как сложность разработки новых решений увеличивается с каждой новой итерацией. 

Предложение: 
После тестирования MVP на реальных примерах можно начать переход к Zammad или OTRS (или различным бесплатным опенсурс CMS) для быстрого внедрения функциональностей, необходимых для аналитиков и других членов команды разработки
